const ROADMAP_DATA=[{week:"Tuần 1-2",title:"Nền tảng Pháp luật",desc:"Hiến pháp 2013, Hệ thống chính trị, Tổ chức bộ máy nhà nước",topics:["Hiến pháp 2013","Hệ thống chính trị","Bộ máy nhà nước"]},{week:"Tuần 3-4",title:"Luật Cán bộ, Công chức",desc:"Luật CBCC 2008 (sửa đổi 2019), Luật Viên chức, Nghị định hướng dẫn",topics:["Luật CBCC","Luật Viên chức","Kỷ luật CC"]},{week:"Tuần 5-6",title:"Luật Kế toán & NSNN",desc:"Luật Kế toán 88/2015, Luật NSNN 83/2015, các Nghị định",topics:["Luật Kế toán","Luật NSNN","NĐ 174/2016"]},{week:"Tuần 7-8",title:"Chế độ KT Hành chính SN",desc:"Thông tư 107/2017/TT-BTC, hệ thống tài khoản, chứng từ, sổ kế toán",topics:["TT 107/2017","Tài khoản KT","Chứng từ"]},{week:"Tuần 9-10",title:"Nghiệp vụ chuyên sâu",desc:"Kế toán ngân sách, Kho bạc, Báo cáo tài chính nhà nước",topics:["TT 77/2017","Kho bạc NN","BCTC"]},{week:"Tuần 11-12",title:"Luyện đề & Ôn tổng hợp",desc:"Làm đề thi thử, xử lý tình huống, rèn kỹ năng thi",topics:["Đề thi thử","Tình huống","Kỹ năng thi"]}];

const STUDY_DATA={round1:[{icon:"📜",title:"Hiến pháp 2013",color:"#3b82f6",items:["Chế độ chính trị (Chương I)","Quyền con người, quyền công dân (Chương II)","Quốc hội, Chính phủ, TAND, VKSND","Chính quyền địa phương"]},{icon:"👔",title:"Luật Cán bộ, Công chức",color:"#8b5cf6",items:["Khái niệm cán bộ, công chức","Nghĩa vụ, quyền của công chức","Tuyển dụng, sử dụng công chức","Kỷ luật công chức - 4 hình thức"]},{icon:"🏛️",title:"Quản lý hành chính",color:"#06b6d4",items:["Nguyên tắc thi hành công vụ","Đạo đức công vụ","Cải cách hành chính","Chính phủ điện tử"]}],round2:[{icon:"📊",title:"Luật Kế toán 2015",color:"#10b981",items:["6 chương, 74 điều","Nguyên tắc kế toán cơ bản","Chứng từ kế toán, sổ kế toán","Báo cáo tài chính, giá trị hợp lý"]},{icon:"💰",title:"Luật Ngân sách NN 2015",color:"#f59e0b",items:["Hệ thống NSNN 4 cấp","Nguyên tắc quản lý NSNN","Lập, chấp hành, quyết toán NS","Bội chi ngân sách địa phương"]},{icon:"📋",title:"TT 107/2017/TT-BTC",color:"#ef4444",items:["Hệ thống 9 loại tài khoản","35 sổ kế toán (7 TH + 28 CT)","Mẫu chứng từ bắt buộc","Báo cáo tài chính & quyết toán"]}]};

const QUIZ_DATA=[{id:"kienthucchung",name:"Kiến thức chung",icon:"📖",count:15,questions:[
{q:"Theo Hiến pháp 2013, cơ quan nào thực hiện quyền lập pháp?",opts:["Chính phủ","Quốc hội","Tòa án nhân dân tối cao","Chủ tịch nước"],ans:1,explain:"Điều 69 Hiến pháp 2013: Quốc hội thực hiện quyền lập hiến, quyền lập pháp."},
{q:"Luật Cán bộ, công chức 2008 (sửa đổi 2019) quy định bao nhiêu hình thức kỷ luật đối với công chức không giữ chức vụ lãnh đạo?",opts:["3 hình thức","4 hình thức","5 hình thức","6 hình thức"],ans:1,explain:"4 hình thức: Khiển trách, Cảnh cáo, Hạ bậc lương, Buộc thôi việc."},
{q:"Theo Luật CBCC sửa đổi 2019, công chức 2 năm liên tiếp không hoàn thành nhiệm vụ thì bị xử lý thế nào?",opts:["Khiển trách","Cảnh cáo","Cho thôi việc","Hạ bậc lương"],ans:2,explain:"Công chức 2 năm liên tiếp xếp loại không hoàn thành nhiệm vụ thì cơ quan có thẩm quyền giải quyết cho thôi việc."},
{q:"Hiến pháp 2013 gồm bao nhiêu chương?",opts:["10 chương","11 chương","12 chương","13 chương"],ans:1,explain:"Hiến pháp 2013 gồm 11 chương, 120 điều."},
{q:"Nguyên tắc nào KHÔNG thuộc 5 nguyên tắc thi hành công vụ?",opts:["Tuân thủ Hiến pháp và pháp luật","Bảo vệ lợi ích Nhà nước","Tự do ngôn luận tuyệt đối","Công khai, minh bạch"],ans:2,explain:"5 nguyên tắc: Tuân thủ HP&PL, bảo vệ lợi ích NN/CD, công khai minh bạch, bảo đảm thứ bậc HC, bảo đảm tính liên tục."},
{q:"Ai có quyền bổ nhiệm Thủ tướng Chính phủ?",opts:["Quốc hội","Chủ tịch nước","Ủy ban Thường vụ Quốc hội","Đảng Cộng sản VN"],ans:1,explain:"Điều 98 HP 2013: Quốc hội bầu Thủ tướng trong số đại biểu Quốc hội theo đề nghị của Chủ tịch nước. Chủ tịch nước bổ nhiệm."},
{q:"Nhiệm kỳ của Quốc hội mỗi khóa là bao nhiêu năm?",opts:["4 năm","5 năm","6 năm","Không giới hạn"],ans:1,explain:"Điều 71 HP 2013: Nhiệm kỳ mỗi khóa Quốc hội là 5 năm."},
{q:"Theo Luật CBCC, công chức là người được tuyển dụng, bổ nhiệm vào ngạch, chức vụ trong cơ quan nào?",opts:["Chỉ cơ quan nhà nước","Cơ quan NN, tổ chức CT, CT-XH","Mọi tổ chức","Doanh nghiệp nhà nước"],ans:1,explain:"Công chức làm việc trong cơ quan nhà nước, tổ chức chính trị, tổ chức chính trị - xã hội."},
{q:"Điểm mới của Luật sửa đổi CBCC 2019 về xử lý kỷ luật cán bộ đã nghỉ hưu?",opts:["Không xử lý","Vẫn bị kỷ luật nếu phát hiện vi phạm","Chỉ phạt tiền","Chỉ khiển trách"],ans:1,explain:"Luật 2019 bổ sung: CB/CC đã nghỉ hưu vẫn bị xử lý kỷ luật nếu phát hiện vi phạm trong thời gian công tác, chống 'hạ cánh an toàn'."},
{q:"Chính quyền địa phương ở Việt Nam gồm mấy cấp?",opts:["2 cấp","3 cấp","4 cấp","5 cấp"],ans:1,explain:"3 cấp: cấp tỉnh, cấp huyện, cấp xã."}
]},{id:"luatketoan",name:"Luật Kế toán",icon:"📊",count:15,questions:[
{q:"Luật Kế toán 2015 (số 88/2015/QH13) có hiệu lực từ ngày nào?",opts:["01/01/2016","01/07/2016","01/01/2017","01/07/2017"],ans:2,explain:"Luật Kế toán 2015 có hiệu lực thi hành từ ngày 01/01/2017."},
{q:"Luật Kế toán 2015 gồm bao nhiêu chương và bao nhiêu điều?",opts:["5 chương, 64 điều","6 chương, 74 điều","7 chương, 80 điều","6 chương, 70 điều"],ans:1,explain:"Luật KT 2015 gồm 6 chương với 74 điều."},
{q:"Điểm mới quan trọng nhất của Luật KT 2015 so với Luật KT 2003?",opts:["Bỏ sổ kế toán","Bổ sung 'giá trị hợp lý'","Bỏ chứng từ giấy","Giảm số tài khoản"],ans:1,explain:"Luật 2015 bổ sung quy định về 'giá trị hợp lý' (fair value) bên cạnh nguyên tắc giá gốc."},
{q:"Kỳ kế toán năm theo Luật KT 2015 là bao nhiêu tháng?",opts:["6 tháng","12 tháng","18 tháng","Tùy đơn vị"],ans:1,explain:"Kỳ kế toán năm là 12 tháng, tính từ đầu ngày 01/01 đến hết ngày 31/12 dương lịch."},
{q:"Đơn vị tiền tệ sử dụng trong kế toán theo Luật KT 2015 là gì?",opts:["USD","Đồng Việt Nam","Tùy chọn","Vàng"],ans:1,explain:"Đơn vị tiền tệ trong kế toán là Đồng Việt Nam (ký hiệu: đ)."},
{q:"Chứng từ điện tử được quy định thế nào trong Luật KT 2015?",opts:["Không được sử dụng","Có giá trị pháp lý như chứng từ giấy","Chỉ dùng tham khảo","Phải in ra giấy mới có giá trị"],ans:1,explain:"Luật 2015 luật hóa chứng từ điện tử, có giá trị pháp lý như chứng từ bằng giấy."},
{q:"Ai chịu trách nhiệm tổ chức bộ máy kế toán của đơn vị?",opts:["Kế toán trưởng","Người đại diện theo PL của đơn vị","Bộ Tài chính","Kiểm toán viên"],ans:1,explain:"Người đại diện theo pháp luật của đơn vị kế toán chịu trách nhiệm tổ chức bộ máy kế toán."},
{q:"Thời hạn lưu trữ tài liệu kế toán tối thiểu là bao lâu?",opts:["3 năm","5 năm","10 năm","Vĩnh viễn"],ans:1,explain:"Tài liệu kế toán phải lưu trữ tối thiểu 5 năm (một số loại 10 năm hoặc vĩnh viễn)."},
{q:"Báo cáo tài chính nhà nước lần đầu được quy định trong luật nào?",opts:["Luật KT 2003","Luật KT 2015","Luật NSNN 2002","Luật NSNN 2015"],ans:1,explain:"Luật KT 2015 lần đầu tiên quy định về báo cáo tài chính nhà nước."},
{q:"Nguyên tắc kế toán cơ bản nhất theo Luật KT 2015?",opts:["Giá gốc","Cơ sở dồn tích","Hoạt động liên tục","Tất cả đáp án trên"],ans:3,explain:"Luật KT 2015 quy định các nguyên tắc: giá gốc, cơ sở dồn tích, hoạt động liên tục, và giá trị hợp lý."}
]},{id:"ngansach",name:"Luật Ngân sách NN",icon:"💰",count:10,questions:[
{q:"Luật NSNN 2015 (số 83/2015/QH13) có hiệu lực từ năm ngân sách nào?",opts:["2016","2017","2018","2019"],ans:1,explain:"Luật NSNN 2015 có hiệu lực từ năm ngân sách 2017."},
{q:"Hệ thống ngân sách nhà nước Việt Nam gồm mấy cấp?",opts:["2 cấp","3 cấp","4 cấp","5 cấp"],ans:2,explain:"4 cấp: Ngân sách trung ương, NS cấp tỉnh, NS cấp huyện, NS cấp xã."},
{q:"Theo Luật NSNN 2015, cấp nào được phép bội chi ngân sách địa phương?",opts:["Cấp xã","Cấp huyện","Cấp tỉnh","Tất cả các cấp"],ans:2,explain:"Chỉ ngân sách cấp tỉnh mới được phép bội chi, chỉ dùng cho đầu tư phát triển."},
{q:"Mức dư nợ vay tối đa của TP.HCM và Hà Nội là bao nhiêu % tổng thu NS được hưởng?",opts:["20%","30%","40%","60%"],ans:3,explain:"HN và TP.HCM: không quá 60%; các ĐP khác: 20-30% tùy khả năng thu."},
{q:"Kế hoạch tài chính trung hạn theo Luật NSNN 2015 là bao nhiêu năm?",opts:["3 năm","5 năm","7 năm","10 năm"],ans:1,explain:"Luật NSNN 2015 đưa vào quy định kế hoạch tài chính 5 năm."},
{q:"Nguyên tắc quản lý NSNN nào sau đây KHÔNG đúng?",opts:["Thống nhất, tập trung","Công khai, minh bạch","Tự do chi tiêu","Tiết kiệm, hiệu quả"],ans:2,explain:"NSNN quản lý thống nhất, tập trung, công khai, minh bạch, tiết kiệm, hiệu quả. Không có 'tự do chi tiêu'."},
{q:"Cơ quan nào giám sát tối cao về NSNN?",opts:["Chính phủ","Quốc hội","Bộ Tài chính","Kiểm toán NN"],ans:1,explain:"Quốc hội thực hiện quyền giám sát tối cao đối với NSNN."},
{q:"Năm ngân sách ở Việt Nam bắt đầu từ ngày nào?",opts:["01/01","01/04","01/07","01/10"],ans:0,explain:"Năm ngân sách bắt đầu từ 01/01 và kết thúc ngày 31/12 dương lịch."}
]},{id:"tt107",name:"Thông tư 107/2017",icon:"📋",count:10,questions:[
{q:"TT 107/2017/TT-BTC áp dụng cho đối tượng nào?",opts:["Doanh nghiệp tư nhân","Cơ quan NN, đơn vị SNCL","Ngân hàng","Tổ chức quốc tế"],ans:1,explain:"TT 107 áp dụng cho cơ quan nhà nước, đơn vị sự nghiệp công lập."},
{q:"Hệ thống tài khoản kế toán theo TT 107 gồm bao nhiêu loại?",opts:["7 loại","8 loại","9 loại","10 loại"],ans:2,explain:"Gồm 9 loại tài khoản trong bảng và các tài khoản ngoài bảng."},
{q:"TT 107 quy định tổng cộng bao nhiêu sổ kế toán?",opts:["25 sổ","30 sổ","35 sổ","40 sổ"],ans:2,explain:"35 sổ kế toán: 7 sổ tổng hợp và 28 sổ chi tiết."},
{q:"TT 107 có hiệu lực từ ngày nào?",opts:["01/01/2017","01/07/2017","01/01/2018","01/07/2018"],ans:2,explain:"TT 107/2017/TT-BTC có hiệu lực từ ngày 01/01/2018."},
{q:"TT 107 thay thế cho văn bản nào?",opts:["QĐ 19/2006/QĐ-BTC","TT 200/2014","TT 133/2016","Luật KT 2003"],ans:0,explain:"TT 107 thay thế QĐ 19/2006/QĐ-BTC và TT 185/2010/TT-BTC."},
{q:"Phương pháp hạch toán theo TT 107 là gì?",opts:["Ghi đơn","Ghi kép (đối ứng)","Ghi theo tiền mặt","Tùy đơn vị"],ans:1,explain:"TT 107 áp dụng phương pháp ghi kép (đối ứng giữa các tài khoản)."},
{q:"Hệ thống sổ chi tiết theo dõi quyết toán trong TT 107 gồm bao nhiêu sổ?",opts:["4 sổ","6 sổ","8 sổ","10 sổ"],ans:1,explain:"6 sổ chi tiết (ký hiệu S101-H đến S106-H) dùng theo dõi số liệu quyết toán."},
{q:"Đơn vị SNCL tự đảm bảo chi thường xuyên và chi đầu tư có thể áp dụng chế độ kế toán nào?",opts:["Chỉ TT 107","Chế độ KT doanh nghiệp","Chuẩn mực KT quốc tế","Không được chọn"],ans:1,explain:"Đơn vị SNCL tự đảm bảo chi TX & chi ĐT có thể vận dụng chế độ KT doanh nghiệp nếu đáp ứng điều kiện."}
]}];

const LAWS_DATA=[
{title:"Luật Kế toán 2015",num:"Số 88/2015/QH13",icon:"📊",color:"#10b981",desc:"Quy định về nội dung công tác kế toán, tổ chức bộ máy kế toán, người làm kế toán. 6 chương, 74 điều.",status:"active",link:"https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Luat-ke-toan-2015-298369.aspx"},
{title:"Luật Ngân sách NN 2015",num:"Số 83/2015/QH13",icon:"💰",color:"#f59e0b",desc:"Quy định về lập, chấp hành, kiểm tra, giám sát, quyết toán ngân sách nhà nước.",status:"active",link:"https://thuvienphapluat.vn/van-ban/Tai-chinh-nha-nuoc/Luat-ngan-sach-nha-nuoc-2015-282814.aspx"},
{title:"Luật Cán bộ, Công chức",num:"Số 22/2008/QH12 (SĐ 2019)",icon:"👔",color:"#8b5cf6",desc:"Quy định về cán bộ, công chức; nghĩa vụ, quyền; tuyển dụng, sử dụng, quản lý.",status:"updated",link:"https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Can-bo-cong-chuc-sua-doi-2019-400400.aspx"},
{title:"Thông tư 107/2017/TT-BTC",num:"Ban hành 10/10/2017",icon:"📋",color:"#3b82f6",desc:"Hướng dẫn chế độ kế toán hành chính, sự nghiệp. Hệ thống tài khoản, chứng từ, sổ kế toán.",status:"active",link:"https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Thong-tu-107-2017-TT-BTC-huong-dan-Che-do-ke-toan-hanh-chinh-su-nghiep-335385.aspx"},
{title:"Nghị định 174/2016/NĐ-CP",num:"Ban hành 30/12/2016",icon:"📄",color:"#06b6d4",desc:"Quy định chi tiết một số điều của Luật Kế toán 2015.",status:"active",link:"https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Nghi-dinh-174-2016-ND-CP-huong-dan-Luat-ke-toan-297990.aspx"},
{title:"Hiến pháp 2013",num:"Ngày 28/11/2013",icon:"📜",color:"#ef4444",desc:"Hiến pháp nước CHXHCN Việt Nam. 11 chương, 120 điều. Nền tảng pháp lý cao nhất.",status:"active",link:"https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Hien-phap-nam-2013-215627.aspx"}
];
